# Preface


The following provides a brief introduction to generalized additive models and some thoughts on getting started with R.  It doesn't assume much more than a basic exposure to regression, and maybe a general idea of R, though not necessarily any particular expertise. The presentation is of a very applied nature, and such that the topics build upon the familiar and generalize to the less so, with the hope that one can bring the concepts they are comfortable with to the new material. The audience in mind is anyone that has some data modeling background and would like to learn more about this type of model.

As this document is more conceptual, a basic familiarity with R is all that is needed to follow the code, though there is much to be gained from having more familiarity.  One should also note that the <span class="pack">tidyverse</span> is used throughout for any data processing that might be shown depicted. And while it wasn't the intention starting out, this document could be seen as a vignette for the <span class="pack">mgcv</span> package, which is highly recommended.

The content of this document is heavily indebted to the first and second editions of Wood's GAM book, and I've tried to keep things up to date with both the package and text.



Color guide:

- *important term*
- [link]()
- <span class="pack">package</span>
- <span class="func">function</span>
- <span class="objclass">object or class</span>


Packages to note:

- data processing
    - <span class="pack">tidyverse</span>
- models
    - <span class="pack">mgcv</span>
    - <span class="pack">lme4</span> * 
    - <span class="pack">mixedup</span> *†
    - <span class="pack">gratia</span> *
- visualization
    - <span class="pack">plotly</span> *
    - <span class="pack">visibly</span> *†
    - <span class="pack">ggeffects</span> *
    - <span class="pack">gratia</span> *

* demo and/or not required
† Personal package
Many others are used behind the scenes.


R Info: **`r sessionInfo()$R.version$version.string` `r sessionInfo()$R.version$nickname`**


This document was last modified `r Sys.Date()`. Original draft August 2012. (@$%* me I've been doing this stuff a while).